# Generated by Django 6.0.3 on 2026-03-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='player_list_json',
            new_name='player_data',
        ),
    ]
